[project]
name = "kv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[dependency-groups]
dev = [
    "black>=24.8.0",
    "mock>=5.2.0",
    "mypy>=1.14.1",
    "pytest>=8.3.5",
    "ruff>=0.11.4",
]
